[ollama]
BASE_URL=http://localhost:11434
; BASE_URL=http://host.docker.internal:11434

[embedding]
device=cpu
; device=cuda
model=nomic-embed-text:latest
; model=intfloat/e5-small-v2
; model=intfloat/e5-base-v2
